# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ElementInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, idBulk: int=None, status: int=None, name: str=None):  # noqa: E501
        """ElementInput - a model defined in Swagger

        :param idBulk: The idBulk of this ElementInput.  # noqa: E501
        :type idBulk: int
        :param status: The status of this ElementInput.  # noqa: E501
        :type status: int
        :param name: The name of this ElementInput.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'idBulk': int,
            'status': int,
            'name': str
        }

        self.attribute_map = {
            'idBulk': 'idBulk',
            'status': 'status',
            'name': 'name'
        }
        self._idBulk = idBulk
        self._status = status
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'ElementInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ElementInput of this ElementInput.  # noqa: E501
        :rtype: ElementInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def idBulk(self) -> int:
        """Gets the idBulk of this ElementInput.


        :return: The idBulk of this ElementInput.
        :rtype: int
        """
        return self._idBulk

    @idBulk.setter
    def idBulk(self, idBulk: int):
        """Sets the idBulk of this ElementInput.


        :param idBulk: The idBulk of this ElementInput.
        :type idBulk: int
        """
        if idBulk is None:
            raise ValueError("Invalid value for `idBulk`, must not be `None`")  # noqa: E501

        self._idBulk = idBulk

    @property
    def status(self) -> int:
        """Gets the status of this ElementInput.


        :return: The status of this ElementInput.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ElementInput.


        :param status: The status of this ElementInput.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def name(self) -> str:
        """Gets the name of this ElementInput.


        :return: The name of this ElementInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ElementInput.


        :param name: The name of this ElementInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
