openapi: 3.0.0
info:
  title: Element Processing API
  description: API for processing elements with status=60
  version: 1.0.0
servers:
- url: /
paths:
  /elements/status-60:
    get:
      summary: Get elements with status=60
      operationId: elements_status60_get
      responses:
        "200":
          description: List of elements with status=60
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Element'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /elements:
    post:
      summary: Insert an element
      operationId: elements_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElementInput'
        required: true
      responses:
        "201":
          description: Element inserted successfully
        "400":
          description: Bad request
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Element:
      type: object
      properties:
        id:
          type: integer
        idBulk:
          type: integer
        retries:
          type: integer
        status:
          type: integer
        name:
          type: string
      example:
        idBulk: 6
        retries: 1
        name: name
        id: 0
        status: 5
    ElementInput:
      required:
      - idBulk
      - name
      - status
      type: object
      properties:
        idBulk:
          type: integer
        status:
          type: integer
        name:
          type: string

